export const CLIENT_LIST_REQUEST = 'CLIENT_LIST_REQUEST';
export const CLIENT_LIST_SUCCESS = 'CLIENT_LIST_SUCCESS';
export const CLIENT_LIST_FAIL = 'CLIENT_LIST_FAIL';

export const CLIENT_SAVE_REQUEST = 'CLIENT_SAVE_REQUEST';
export const CLIENT_SAVE_SUCCESS = 'CLIENT_SAVE_SUCCESS';
export const CLIENT_SAVE_FAIL = 'CLIENT_SAVE_FAIL';

export const SERVICE_LIST_REQUEST = 'SERVICE_LIST_REQUEST';
export const SERVICE_LIST_SUCCESS = 'SERVICE_LIST_SUCCESS';
export const SERVICE_LIST_FAIL = 'SERVICE_LIST_FAIL';

export const SERVICE_SAVE_REQUEST = 'SERVICE_SAVE_REQUEST';
export const SERVICE_SAVE_SUCCESS = 'SERVICE_SAVE_SUCCESS';
export const SERVICE_SAVE_FAIL = 'SERVICE_SAVE_FAIL';

export const INVOICE_SAVE_REQUEST = 'INVOICE_SAVE_REQUEST';
export const INVOICE_SAVE_SUCCESS = 'INVOICE_SAVE_SUCCESS';
export const INVOICE_SAVE_FAIL = 'INVOICE_SAVE_FAIL';

export const INVOICE_LIST_REQUEST = 'INVOICE_LIST_REQUEST';
export const INVOICE_LIST_SUCCESS = 'INVOICE_LIST_SUCCESS';
export const INVOICE_LIST_FAIL = 'INVOICE_LIST_FAIL';